### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by CharlyJazz** [CharlyJazz/Flask-MVC-Template#1]

**Comment by CharlyJazz** [comment]
Update the versions. And evaluate if the unit tests do not break. Example, I think the current Flask version is very old. It would be better to use the most recent version.

**Comment by alessandrojcm** [comment]
I can tackle this, I'm currently working on a Flask project which uses the latest version. Would you also consider adding another dependency management tool? Like Pipenv or Pypoetry (I personalle prefer pypoetry).

**Comment by CharlyJazz** [comment]
Sure, describe in the pull request the advantages of pypoetry and let's see how it works in this project!

I am open to any suggestion and new features! :100:

**Comment by alessandrojcm** [comment]
Cool! Could you please asign me this issue?

**Comment by CharlyJazz** [comment]
Done. Check your email

**Comment by alessandrojcm** [comment]
Gracias 😉 Which Python version should we fix the project to? I think 3.6 It's ok, 3.7 is not really neccesary unless you are using dataclasses. Or should it keep backwards compatibility with 2.7?

**Comment by CharlyJazz** [comment]
We should discuss it with @Danushka96 

There are still many people who use 2.7 but I do not know if any dependency no longer supports it.

You should use the TLS version of python 3. And Danuska will work on configuring the CI to test the project in different versions of Python

**Comment by alessandrojcm** [comment]
Cool, I'll keep it backwards compatible. Regarding the dependencies, normally al Flask-related modules try to keep it backwards compatible with 2.7, we'll see when we update.

**Comment by CharlyJazz** [comment]
Go ahead!

**Comment by alessandrojcm** [comment]
So I've hit the first problem (Flask-Via)[https://github.com/thisissoon/Flask-Via] is not compatible, I checked and you are already working on it. So I guess I should pause this until you're done? :thinking:

**Comment by CharlyJazz** [comment]
Hmm

Nothing is a casuality. We can join forces. Would you like to check in Flask-via that is not compatible with the latest version of Flask?

Find me on a telegram to talk @charlyjazz

**Comment by alessandrojcm** [comment]
Sure! 

⁣Enviado desde BlueMail ​

**Comment by CharlyJazz** [comment]
I going to close this issue to unify this problem with a update plan
