### ISSUE TITLE
Add Travis CI or Circle CI for run test and python versions

### ISSUE THREAD

**Issue by CharlyJazz** [CharlyJazz/Flask-MVC-Template#3]

**Comment by Danushka96** [comment]
I will config the Travis CI with python versions. Could you assign this issue to me?

**Comment by CharlyJazz** [comment]
Sure, bro! Check your email

**Comment by Danushka96** [comment]
You don't want to add me to the contribution list. I accepted. But It's good if you removed from contribution list 👍

**Comment by CharlyJazz** [comment]
Done!

**Comment by CharlyJazz** [comment]
Hahaha, I think I can not assign you the issue if you're not on the list. Automatically the assignment was removed

**Comment by Danushka96** [comment]
Assign this issue to me. I will create a pull request ASAP.

**Comment by CharlyJazz** [comment]
I cant assign a issue if you dont exist in the colaborator list, let me send the invitatin again hahaha

**Comment by CharlyJazz** [comment]
Check your email :hamburger:

**Comment by Danushka96** [comment]
I made a pull request, if it's ok merge it and test
